extern crate ez_pixmap;
extern crate image;

pub const RUSTLOGO: &[&str] = &[
"144 144 64 1 ",
"  c black",
". c #040404",
"X c gray3",
"o c gray6",
"O c gray7",
"+ c gray9",
"@ c #191919",
"# c #1D1D1D",
"$ c gray13",
"% c #252525",
"& c #282828",
"* c #2F2F2F",
"= c gray20",
"- c #353535",
"; c #3A3A3A",
": c #3E3E3E",
"> c #434343",
", c gray27",
"< c gray29",
"1 c #4C4C4C",
"2 c #515151",
"3 c #555555",
"4 c gray35",
"5 c #5D5D5D",
"6 c gray38",
"7 c #646464",
"8 c #6A6A6A",
"9 c #6F6F6F",
"0 c #717171",
"q c gray46",
"w c #7B7B7B",
"e c gray50",
"r c gray51",
"t c #868686",
"y c #888888",
"u c gray56",
"i c #909090",
"p c gray58",
"a c #9B9B9B",
"s c #9F9F9F",
"d c gray64",
"f c #A4A4A4",
"g c gray66",
"h c #AFAFAF",
"j c gray69",
"k c gray71",
"l c #B9B9B9",
"z c gray75",
"x c gray76",
"c c gray77",
"v c #CBCBCB",
"b c #CDCDCD",
"n c #D0D0D0",
"m c #D5D5D5",
"M c #DADADA",
"N c gray87",
"B c #E2E2E2",
"V c #E6E6E6",
"C c #E9E9E9",
"Z c #ECECEC",
"A c #F1F1F1",
"S c #F6F6F6",
"D c gray98",
"F c white",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFdoXdFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFa<uDFFFFFFFFM.  .MFFFFFFFFFu<pFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFh   6FFFFFFFF>    >FFFFFFFF7   jFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF,    9FFFFFFd      dFFFFFFq    ,FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB      tFFFFZ+      +CFFFFt      NFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFu;0AFFFFFFFr       aFFF7        6FFFa       rFFFFFFFZq;uFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFk   $cFFFFFF%        fSk          jSf        $FFFFFFc$   kFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFq     wDFFFx                                  xFFFFi.    qFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<      -NFF7                                  7FFB:      <FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF$       Ot3.                                  .2tO       $FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFS                                                          AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVaxFFFFFFFb                                                          bFFFFFFFxaVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFV+  =dDFFFFd                          .1r0%                           dFFFFDf=  +VFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf     #uAFF0                         @nFFFDw                          0FFAu#     dFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFs       Oq1                          vFFFFFF4                          <qO       sFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFg                                   >FFFFFFFv                                    fFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFj                                   8FFFFFFFS                                    hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFl                                   4FFFFFFFV                                    kFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFx                                   +AFFFFFFi                                    xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFv                            #42     4DFFFFmO     65%                            vFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFB2-6sMFFFFc                        O5fVFFF5     >kVMyo     tFFFZf6@                        xFFFFMs6-2BFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFF2     @2ig+                     O8lDFFFFFFD3              iFFFFFFFFz8O                     +gi3+     2FFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFF=                             -sSFFFFFFFFFFD<            sFFFFFFFFFFFDf:                             =FFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFF6                           2vFFFFFFFFFFFFFFS:          fFFFFFFFFFFFFFFFv2                           5FFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFs                         >vFFFFFFFFFFFFFFFFFS:       .hFFFFFFFFFFFFFFFFFFm3                         sFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFM                       *xFFFFFFFFFFFFFFFFFFFFZ=     XlFFFFFFFFFFFFFFFFFFFFFx=                       MFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFF+                    XyDFFFFFFFFFFFFFFFFFFFFFFC;   @cFFFFFFFFFFFFFFFFFFFFFFFDio                    +FFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFF2                   ,NFFFFFFFFFFFFFFFFFFFFFFFFFFxpjSFFFFFFFFFFFFFFFFFFFFFFFFFFB>                   2FFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFu                 .tFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFu.                 uFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFg                @xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFc#                gFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFVdsghlzvx+               -VFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC;               +xbxlhgsdVFFFFFFFFFFFFF",
"FFFFFFFFFFFFV+                       1SFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFS3                       +BFFFFFFFFFFFF",
"FFFFFFFFFFFFa                       8DFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5                       sFFFFFFFFFFFF",
"FFFFFFFFFFFFx                      9FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF6                      xFFFFFFFFFFFF",
"FFFFFFFFFFFFF=                    6FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF8                    *FFFFFFFFFFFFF",
"FFFFFFFFFFFFFd                   ,MNNNNNNNNNNNNNNNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNSFFFFFFFFFFFFFFFFFFFF6                   fFFFFFFFFFFFFF",
"FFFFFFFFFFFFFD#                                                                           +<evFFFFFFFFFFFFFFFFD,                 @DFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFu                                                                               $wMFFFFFFFFFFFFFFA*                uFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFAo                                                                                 3MFFFFFFFFFFFFFMo              oAFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFq                                                                                  XeDFFFFFFFFFFFFh              qFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFF1                                                                                    >CFFFFFFFFFFFF8             1FFFFFFFFFFFFFFF",
"FFFFFFFFFFFSbf0                                                                                      @vFFFFFFFFFFFS%             0fbSFFFFFFFFFFF",
"FFFFFFFlq<$                                                                                           ovFFFFFFFFFFFc                 $<qlFFFFFFF",
"FFFFFFu                                                                                                ONFFFFFFFFFFF6                    uFFFFFF",
"FFFFFF;                                                                                                 *SFFFFFFFFFFCo                   ;FFFFFF",
"FFFFFF0                                                                                                  rFFFFFFFFFFM                    0FFFFFF",
"FFFFFFA$                                                                                                 XBFFFFFFFFF7                   $ZFFFFFF",
"FFFFFFFv.                                                                                                 qFFFFFFFFZX                  .cFFFFFFF",
"FFFFFFFFr                                                                                                 ODFFFFFFFt                   rFFFFFFFF",
"FFFFFFFFF:                                                                                                 vFFFFFFD@                  :DFFFFFFFF",
"FFFFFFFFFBO         *,$                                                                                    tFFFFFFd      oo          OBFFFFFFFFF",
"FFFFFFFFFFt       *bFFFk+    &7777774                       XOOOOOOoOOoOoOOOOo                             7FFFFFF=    *lFFm3        tFFFFFFFFFF",
"FFFFFFFFFF2      @ZFFFFFn.   #FFFFFFM                       cFFFFFFFFFFFFFFFFFZl5X                         2FFFFFz    *AFFFFF8       2FFFFFFFFFF",
"FFFFFFFFc7X      uFFFFFFF4    gFFFFFM                       cFFFFFFFFFFFFFFFFFFFFM;                        ,FFFFF1    lFFFFFFAo      .7cFFFFFFFF",
"FFFFFBr$         cFFFFFFFp    ;FFFFFN                       cFFFFFFFFFFFFFFFFFFFFFS;                       6FFFFM    .FFFFFFFF<         $rBFFFFF",
"FFFh>            xFFFFFFFi     cFFFFM                       cFFFFFFFFFFFFFFFFFFFFFFb                       eFFFF8    oFFFFFFFF2            >hFFF",
"FFa              wFFFFFFF<     9FFFFM                       cFFFFFFFFFFFFFFFFFFFFFFFO                      xFFFSO     nFFFFFFF#              aFF",
"FF<              oMFFFFFl      4FFFFN                       cFFFFFFFFFFFFFFFFFFFFFFF@                     OFFFFB      3FFFFFFa               1FF",
"FFu               @gDFSpX      tFFFFM                       cFFFFFFFFFFFFFFFFFFFFFFm                      rFFFFFX      7AFFFa.               uFF",
"FFD6                o$.       +ZFFFFM                       cFFFFFFFFFFFFFFFFFFFFFA;                     +AFFFFF9       o12#                6FFF",
"FFFFq                        &vFFFFFN                       cFFFFFFFFFFFFFFFFFFFFl*                      fFFFFFFA<                         qFFFF",
"FFFFFt                     :hDFFFFFFM                       izlllzlllzlzlllzldy7$                       6FFFFFFFFFl,                      tFFFFF",
"FFFFFFa                  1cFFFFFFFFFM                                                                  >SFFFFFFFFFFFM9X                  iFFFFFF",
"FFFFFFFg              OqBFFFFFFFFFFFN                                                                 ;AFFFFFFFFFFFFFFCr+               gFFFFFFF",
"FFFFFFFA            $iAFFFFFFFFFFFFFM                                                                ,AFFFFFFFFFFFFFFFFFSa*             SFFFFFFF",
"FFFFFFFk            lFFFFFFFFFFFFFFFM                                                               8DFFFFFFFFFFFFFFFFFFFFFp            kFFFFFFF",
"FFFFFZ7             bFFFFFFFFFFFFFFFM                                                             ofFFFFFFFFFFFFFFFFFFFFFFFc             7ZFFFFF",
"FFFFd+              VFFFFFFFFFFFFFFFM                                                            >BFFFFFFFFFFFFFFFFFFFFFFFFm              +dFFFF",
"FFM,                ZFFFFFFFFFFFFFFFM                                                            3SFFFFFFFFFFFFFFFFFFFFFFFFB                :mFF",
"Ff.                 AFFFFFFFFFFFFFFFN                                                             -VFFFFFFFFFFFFFFFFFFFFFFFZ                 .fF",
"Do                  DFFFFFFFFFFFFFFFM                                                              #nFFFFFFFFFFFFFFFFFFFFFFD                  oD",
"FX                  SFFFFFFFFFFFFFFFM                                                               +MFFFFFFFFFFFFFFFFFFFFFA                  oD",
"Fd.                 CFFFFFFFFFFFFFFFN                                                                &AFFFFFFFFFFFFFFFFFFFFC                 .dF",
"FFM,                BFFFFFFFFFFFFFFFM                                                                 8FFFFFFFFFFFFFFFFFFFFB                :nFF",
"FFFFd+              nFFFFFFFFFFFFFFFN                                                                  nFFFFFFFFFFFFFS977773              +dFFFF",
"FFFFFC6             lFFFFFFFFFFFFFFFM                       %=============#.                           5FFFFFFFFFFFFFx                   6ZFFFFF",
"FFFFFFFk            dFFFFFFFFFFFFFFFM                       cFFFFFFFFFFFFFFAg-                         .CFFFFFFFFFFFFx                  kFFFFFFF",
"FFFFFFFA            rFFFFFFFFFFFFFFFM                       vFFFFFFFFFFFFFFFFFi.                        aFFFFFFFFFFFFx                  AFFFFFFF",
"FFFFFFFg            5FFFFFFFFFFFFFFFN                       cFFFFFFFFFFFFFFFFFFd                        1FFFFFFFFFFFFj                  gFFFFFFF",
"FFFFFFa             =FFFFFFFFFFFFFFFM                       vFFFFFFFFFFFFFFFFFFF7                       XFFFFFFFFFFFFs                  .aFFFFFF",
"FFFFFy              .DFFFFFFFFFFFFFFM                       cFFFFFFFFFFFFFFFFFFFZ+                       bFFFFFFFFFFF7                    yFFFFF",
"FFFFq                nFFFFFFFFFFFFFFN                       cFFFFFFFFFFFFFFFFFFFF8                       aFFFFFFFFFFD@                     qFFFF",
"FFF7                 pFFFFFFFFFFFFFFM                       cFFFFFFFFFFFFFFFFFFFFx                       2FFFFFFFFFFt                       7FFF",
"FFu                  2FFFFFFFFFFFFFFM                       cFFFFFFFFFFFFFFFFFFFFDo                       iFFFFFFFFs                         uFF",
"FF1                  +bbvbvbvbvbvvvbj                       cFFFFFFFFFFFFFFFFFFFFF:                        :fZFFNf,                          1FF",
"FFp                                                         ,333333333333xFFFFFFFFq                           oo                             aFF",
"FFFh>                                                                    uFFFFFFFFg                                                        ,jFFF",
"FFFFFBt%                                                                 yFFFFFFFFN                                                     #qNFFFFF",
"FFFFFFFFx7X                                                              uFFFFFFFFF+                                                 .6xFFFFFFFF",
"FFFFFFFFFF2                                                              yFFFFFFFFF1                                                 3FFFFFFFFFF",
"FFFFFFFFFFt                                                              uFFFFFFFFFt                                                 tFFFFFFFFFF",
"FFFFFFFFFBO                                                              uFFFFFFFFFz                                                 OBFFFFFFFFF",
"FFFFFFFFD>                                                               yFFFFFFFFFSX                                                 ;FFFFFFFFF",
"FFFFFFFFr                                                                yFFFFFFFFFF,                                                  rFFFFFFFF",
"FFFFFFFc.                                                                uFFFFFFFFFFd                                                   cFFFFFFF",
"FFFFFFA$                                                                 yFFFFFFFFFFD$                                                  #ZFFFFFF",
"FFFFFF0                                                                  uFFFFFFFFFFFf                                                   0FFFFFF",
"FFFFFF;                                                                  uFFFFFFFFFFFF5                                                  ;FFFFFF",
"FFFFFFu                                                                  yFFFFFFFFFFFFA%                                                 uFFFFFF",
"FFFFFFFl0<$                                                              uFFFFFFFFFFFFFB%                                            #<qlFFFFFFF",
"FFFFFFFFFFFSbd0                                                          uFFFFFFFFFFFFFFA7.                                      0dbSFFFFFFFFFFF",
"FFFFFFFFFFFFFFF<              4aapapaaaaaaapaapaaaapapaaapapaaaaapaaaapaaBFFFFFFFFFFFFFFFFVhpaaaaaapapaaaapaaaapa5              <FFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFq              +BFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFN+              qFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFAO               =SFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD-               oZFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFu                 3FFFFFFFFFFmvDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFD3                 uFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFD#                  9FFFFVjw:o  +pFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDe+ $4icSFFFFF9                  #DFFFFFFFFFFFFF",
"FFFFFFFFFFFFFf                    0u3#         sFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF3       .=9dMr                    dFFFFFFFFFFFFF",
"FFFFFFFFFFFFF*                                 $FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFz                                  *FFFFFFFFFFFFF",
"FFFFFFFFFFFFx                                   NFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFq                                   xFFFFFFFFFFFF",
"FFFFFFFFFFFFs                                   fFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF:                                   sFFFFFFFFFFFF",
"FFFFFFFFFFFFB+                        <gcf>     0FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDo     ,yu2                         +VFFFFFFFFFFFF",
"FFFFFFFFFFFFFVfaghlxbx+              rFFFFFe    ;FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFn    .jFFFFcO              +xvxlhgafVFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFf             :FFFFFFF;   XDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFs    uFFFFFFg              fFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFu             aFFFFFFFp    bFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF7   XSFFFFFFF+             iFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFF2             jFFFFFFFj    pFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF*   %FFFFFFFF>             3FFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFF+             uFFFFFFFu    5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA.   OFFFFFFFF&             @FFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFM              *DFFFFFD&    &FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFx     kFFFFFFb               mFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFs               5DFFFS5      mFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFy     #BFFFFZ*               sFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFF6                %tdr%       .1lFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDg,       +ybni#                6FFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFF=                               $enFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFm0+                               -FFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFF2     +2ug+                        &qlSFFFFFFFFFFFFFFFFFFFFFFFFAg7$                        +gi2+     2FFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFB2-6sMFFFFc                           .:0dnSFFFFFFFFFFFFFFSnd0;.                           xFFFFMs6-2BFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFv                                 @;26qwttqq61;@                                 vFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFx                                                                                xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFl                                                                                lFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFj                                                                                hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf                                                                                fFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFs       o01                                                            <qo       sFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFf     #uAFF0                                                          9FFAu#     fFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFV+  *dDFFFFd                                                          dFFFFDd=  +VFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFVaxFFFFFFFb                                                          vFFFFFFFxaVFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFS                                                          SFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF$       or3X                                  .3tO       #FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF<      ;NFF7                                  7FFB>      <FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFq    .rDFFFx                                  xFFFFi.    qFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFl   $cFFFFFF$        fSk          jSg        $FFFFFFc$   kFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFu;0AFFFFFFFr       aFFF7        7FFFa       rFFFFFFFA0;uFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFB      yFFFFZ@      OZFFFFu      NFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF>    wFFFFFFd      dFFFFFFw    >FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFj   7FFFFFFFF>    >FFFFFFFF7   hFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFa1uFFFFFFFFFM.  .mFFFFFFFFFi1aFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFfoodFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
"FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFDDFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
];

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let my_image = ez_pixmap::RgbaImage::new(RUSTLOGO)?;
    image::save_buffer(
        "examples/image2.png",
        my_image.data(),
        my_image.width(),
        my_image.height(),
        image::ColorType::Rgba8,
    )?;
    Ok(())
}
